# Personal info
site_name: izlyforever
site_author: izlyforever
site_url: https://izlyforever.github.io/cpplibforCP
repo_url: https://github.com/izlyforever/cpplibforCP

copyright: Copyright © 2021 izlyforever

# Contents
nav:
  - Home:
    - Introduction: index.md
  - Math:
    - basic: math/basic.md
    - primary: math/primary.md
    - numberTheory: math/numberTheory.md
    - mod: math/mod.md
    - poly: math/poly.md
    - mixed: math/mixed.md
    - geometry: math/geometry.md
  - Data Structure: dataStructure.md
  - Graph Theory: graph.md
  - String: string.md
  - CN: cn.md

theme:
  name: darkly

markdown_extensions:
  - mdx_math:
      enable_dollar_delimiter: True

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

plugins:
  - search